groups: 
- name: delivery
  jobs:
  - unit-tests
  - compile-smoke
  - deploy-stage
  - load-test
- name: deployment
  jobs:
  - shipit

resources:
- name: concourse-demo-app-master
  type: git
  source:
    branch: master
    private_key: ((github-private-key))
    uri: git@github.com:95rade/concourse-demo-app.git

- name: staging
  type: cf
  source:
    api: ((cf-api))
    organization: ((cf-organization))
    username: ((cf-username))
    password: ((cf-password))
    skip_cert_check: true
    space: ((cf-space))

- name: production
  type: cf
  source:
    api: ((cf-api))
    organization: ((cf-organization))
    username: ((cf-username))
    password: ((cf-password))
    skip_cert_check: true
    space: ((cf-space))

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-demo-app-master 
    trigger: true
  - task: unit-tests
    file: concourse-demo-app-master/ci/unit.yml

- name: compile-smoke 
  serial: true
  public: true
  plan:
  - get: concourse-demo-app-master 
    trigger: true
    passed:
      - unit-tests
  - task: compile-smoke
    file: concourse-demo-app-master/ci/compile.yml

- name: deploy-stage
  serial: true
  plan:
  - get: concourse-demo-app-master
    trigger: true
    passed:
      - compile-smoke
  - put: staging
    params:
      manifest: concourse-demo-app-master/manifests/staging.yml
      path: concourse-demo-app-master
      current_app_name: demo-app-stage

- name: load-test 
  public: true
  plan:
  - get: concourse-demo-app-master
    trigger: true
    passed:
      - deploy-stage
  - task: load-test 
    file: concourse-demo-app-master/ci/load.yml
    # don't need both 'file' and 'config' in task step !
    #config:
    #  params: 
    #    "CFUSER": ((cf-username))
    #    "CFPASS": ((cf-password))
    #    "ORG": ((cf-organization))
    #    "SPACE": ((cf-space))
    #    "API": ((cf-api))
    #    "APPNAME": demo-app-stage
- name: shipit
  plan:
  - get: concourse-demo-app-master
    trigger: true
    passed:
      - load-test
  - put: production
    params:
      manifest: concourse-demo-app-master/manifests/prod.yml
      path: concourse-demo-app-master
      current_app_name: demo-app-prod
